### ISSUE TITLE
installing error on mac

### ISSUE THREAD

**Issue by klkim** [metstrike/meteor-oracle#12]
This is the same issue with #7, #11.
Your solution proposed,
$ cd ~/workspace
$ git clone https://github.com/metstrike/meteor-oracle.git
$ export PACKAGE_DIRS="~/workspace"

$ cd ~/workspace/todos-oracle
$ meteor add metstrike:meteor-oracle

seems not to work.

I suspect the "LD_LIBRARY_PATH" environmental variable on mac.
i.e. export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<PATH-TO-YOUR-ORACLE-INSTANT-CLIENT>/instantclient_11_2/

Any suggestions?

Thank you.

**Comment by metstrike** [comment]
Thank you for the follow-up question. I was able to make it working on mac, there will be couple of things to try. First thing is, please follow the installation instructions in paragraph 5.3.1 of https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

Then try to set the following environment variables before running meteor for the first time.

export OCI_LIB_DIR=/usr/local/lib
export OCI_INC_DIR=/opt/oracle/instantclient_11_2/sdk/include

Also, please let me know your OSX version, because Yosemite, might have behave a little different than El Capitan.

**Comment by klkim** [comment]
I'm using a OS X El Capitan(10.11.4). Let me try and I'll report here soon. 
Thank you.

**Comment by klkim** [comment]
It' not working. I followed the steps above link said 5.3.1 or 5.3.2.

In node.js, everything is well installed using "npm install oracledb" with prerequisite oracle-related installation.

Anyway, I'll try it again in different way or clean installation. :)

**Comment by metstrike** [comment]
Ok, now let's try another thing.

To eliminate the headache of having to manually check out the meteor-oracle package, I have finally published to AtmosphereJS the package prebuilt for OSX platform.

Please try the following steps and let me know if any error occurs. These steps worked for me on OSX Yosemite with installed Oracle instant client 11.2.

```
$ cd ~/workspace
$ git clone https://github.com/metstrike/todos-oracle.git
$ cd todos-oracle

# Edit the connection information to your Oracle DB schema, the schema has to be created
$ vi lib/collections.js

$ meteor
```

The package should now be automatically downloaded from the AtmosphereJS and there is no need to set any PACKAGE_DIRS, DYLD_LIBRARY_PATH, or LD_LIBRARY_PATH variables.

**IMPORTANT NOTE**
The published package assumes though that the instant client 11.2.0.4 has been installed according to the instructions to the directory **/opt/oracle/instantclient_11_2** and symbolic links have been deployed to the directory **/usr/local/lib**. Please make sure your symbolic links look as follows:

```
$ ls -l /usr/local/lib
lrwxr-xr-x  1 root  wheel   51 Mar 20 21:12 libclntsh.dylib -> /opt/oracle/instantclient_11_2/libclntsh.dylib.11.1
lrwxr-xr-x  1 root  wheel   51 Mar 26 22:43 libclntsh.dylib.11.1 -> /opt/oracle/instantclient_11_2/libclntsh.dylib.11.1
lrwxr-xr-x  1 root  wheel   45 Mar 26 22:41 libnnz11.dylib -> /opt/oracle/instantclient_11_2/libnnz11.dylib
lrwxr-xr-x  1 root  wheel   45 Mar 26 22:42 libociei.dylib -> /opt/oracle/instantclient_11_2/libociei.dylib
```

**Comment by klkim** [comment]
SUCCESS with your first suggestion!
After reviewing again, I will summarize the way I choose, here soon.

Thank you again. :)

**Comment by klkim** [comment]
I followed below steps to install this wonderful package in meteor on OS X(El Capitan).

1.
Go to the link https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#-532-install-instant-client-in-a-user-directory
and followed the steps 5.3.2 (this is already commented by metstrike)

2.
Set the environmental variable.
$ export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:~/instantclient_11_2/

Check the value using $ echo $DYLD_LIBRARY_PATH

That's it. :)

**Comment by metstrike** [comment]
Thank you for providing the specific steps that worked for you. I am sure other developers will find it useful. With next release I will copy your instructions to README.md.

I am glad, that DYLD_LIBRARY_PATH can still be used on El Capitan, I heard that it was deprecated due to security.

**Comment by gazpachu** [comment]
I'm getting this with MacOS Sierra:

```
W20170111-13:08:35.158(1)? (STDERR)           
W20170111-13:08:35.158(1)? (STDERR) /Users/martosj/.meteor/packages/meteor-tool/.1.1.10.grprbk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20170111-13:08:35.159(1)? (STDERR) 						throw(ex);
W20170111-13:08:35.159(1)? (STDERR) 						      ^
W20170111-13:08:35.161(1)? (STDERR) Error: dlopen(/Users/martosj/.meteor/packages/metstrike_meteor-oracle/.0.2.0.rpf7ma++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/oracledb/build/Release/oracledb.node, 1): Library not loaded: /ade/b/3071542110/oracle/rdbms/lib/libclntsh.dylib.11.1
W20170111-13:08:35.161(1)? (STDERR)   Referenced from: /Users/martosj/.meteor/packages/metstrike_meteor-oracle/.0.2.0.rpf7ma++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/oracledb/build/Release/oracledb.node
W20170111-13:08:35.161(1)? (STDERR)   Reason: image not found
W20170111-13:08:35.161(1)? (STDERR)     at Module.load (module.js:356:32)
W20170111-13:08:35.162(1)? (STDERR)     at Function.Module._load (module.js:312:12)
W20170111-13:08:35.162(1)? (STDERR)     at Module.require (module.js:364:17)
W20170111-13:08:35.162(1)? (STDERR)     at require (module.js:380:17)
W20170111-13:08:35.162(1)? (STDERR)     at Object.<anonymous> (/Users/martosj/.meteor/packages/metstrike_meteor-oracle/.0.2.0.rpf7ma++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/oracledb/lib/oracledb.js:23:15)
W20170111-13:08:35.162(1)? (STDERR)     at Module._compile (module.js:456:26)
W20170111-13:08:35.162(1)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20170111-13:08:35.162(1)? (STDERR)     at Module.load (module.js:356:32)
W20170111-13:08:35.162(1)? (STDERR)     at Function.Module._load (module.js:312:12)
W20170111-13:08:35.162(1)? (STDERR)     at Module.require (module.js:364:17)
=> Exited with code: 8

```

**Comment by cjbj** [comment]
@gazpachu It might have been better to open a new issue.

Anyway, you need to use Oracle Instant Client 12.1 on OS X since Apple's SIP broke some dynamic loading feature. See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx

**Comment by gazpachu** [comment]
Thanks @cjbj I'm already using Oracle Instant Client 12.1 but it seems the TODOS example is not. How can I update that?

Sorry, I've opened a new issue here: https://github.com/metstrike/todos-oracle/issues/1 but since this thread also talks about Mac installation issues, I thought it could be useful to have an updated experience.

**Comment by gazpachu** [comment]
I get this error when running `meteor update`:

```
E0346624:todos-oracle martosj$ meteor update
=> Errors while initializing project:         
                                              
While loading package metstrike:meteor-oracle@0.2.0:
error: Command failed:
/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
rebuild --update-binary
node-oracledb ERR! Error: Cannot find $OCI_LIB_DIR/libclntsh.dylib
node-oracledb ERR! Error: Do you need to run 'cd $OCI_LIB_DIR && ln -s libclntsh.dylib.* libclntsh.dylib'?
node-oracledb ERR! Error: See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx

gyp: Call to 'INSTURL="https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx"; ERR="node-oracledb ERR! Error:"; if [ -z
$OCI_LIB_DIR ]; then if [ -f /opt/oracle/instantclient/libclntsh.dylib ]; then echo "/opt/oracle/instantclient/"; else echo "$ERR Cannot
find /opt/oracle/instantclient/libclntsh.dylib" >&2; echo "$ERR Do you need to run 'cd /opt/oracle/instantclient && ln -s libclntsh.dylib.*
libclntsh.dylib'?" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; else if [ -f "$OCI_LIB_DIR/libclntsh.dylib" ]; then echo
$OCI_LIB_DIR; else echo "$ERR Cannot find \$OCI_LIB_DIR/libclntsh.dylib" >&2; echo "$ERR Do you need to run 'cd \$OCI_LIB_DIR && ln -s
libclntsh.dylib.* libclntsh.dylib'?" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; fi;' returned exit status 0 while in binding.gyp.
while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command
"/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/Users/martosj/.meteor/packages/metstrike_meteor-oracle/.0.2.0.rpf7ma++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-n7gdjb/node_modules/oracledb
gyp ERR! node -v v4.6.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 16.3.0
npm ERR! argv
"/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--update-binary"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! oracledb@1.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oracledb@1.6.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/martosj/.meteor/packages/metstrike_meteor-oracle/.0.2.0.rpf7ma++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-n7gdjb/npm-debug.log
node-oracledb ERR! Error: Cannot find $OCI_LIB_DIR/libclntsh.dylib
node-oracledb ERR! Error: Do you need to run 'cd $OCI_LIB_DIR && ln -s libclntsh.dylib.* libclntsh.dylib'?
node-oracledb ERR! Error: See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx

gyp: Call to 'INSTURL="https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx"; ERR="node-oracledb ERR! Error:"; if [ -z
$OCI_LIB_DIR ]; then if [ -f /opt/oracle/instantclient/libclntsh.dylib ]; then echo "/opt/oracle/instantclient/"; else echo "$ERR Cannot
find /opt/oracle/instantclient/libclntsh.dylib" >&2; echo "$ERR Do you need to run 'cd /opt/oracle/instantclient && ln -s libclntsh.dylib.*
libclntsh.dylib'?" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; else if [ -f "$OCI_LIB_DIR/libclntsh.dylib" ]; then echo
$OCI_LIB_DIR; else echo "$ERR Cannot find \$OCI_LIB_DIR/libclntsh.dylib" >&2; echo "$ERR Do you need to run 'cd \$OCI_LIB_DIR && ln -s
libclntsh.dylib.* libclntsh.dylib'?" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; fi;' returned exit status 0 while in binding.gyp.
while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command
"/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/Users/martosj/.meteor/packages/metstrike_meteor-oracle/.0.2.0.rpf7ma++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-n7gdjb/node_modules/oracledb
gyp ERR! node -v v4.6.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 16.3.0
npm ERR! argv
"/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--update-binary"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! oracledb@1.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oracledb@1.6.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/martosj/.meteor/packages/metstrike_meteor-oracle/.0.2.0.rpf7ma++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-n7gdjb/npm-debug.log

```

**Comment by gazpachu** [comment]
I've managed to complete the `meteor update` and the node-oracle examples work

```
E0346624:oracle-examples martosj$ node connect.js
Connection was successful!
```

But now I get another error in the TODOS example :(

```
W20170111-13:44:03.664(1)? (STDERR) /Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170111-13:44:03.664(1)? (STDERR) 						throw(ex);
W20170111-13:44:03.665(1)? (STDERR) 						^
W20170111-13:44:03.666(1)? (STDERR) 
W20170111-13:44:03.666(1)? (STDERR) TypeError: callback is not a function
W20170111-13:44:03.667(1)? (STDERR)     at [object Object].OracleCollection.Cursor.count (packages/metstrike_meteor-oracle.js:1236:4)
W20170111-13:44:03.667(1)? (STDERR)     at SynchronousCursor.fn [as _synchronousCount] (/Users/martosj/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:93:26)
W20170111-13:44:03.668(1)? (STDERR)     at SynchronousCursor.count (packages/mongo/mongo_driver.js:1097:17)
W20170111-13:44:03.669(1)? (STDERR)     at Cursor.(anonymous function) [as count] (packages/mongo/mongo_driver.js:907:44)
W20170111-13:44:03.669(1)? (STDERR)     at app/server/bootstrap.js:3:20
W20170111-13:44:03.669(1)? (STDERR)     at Function.time (/Users/martosj/Dev/Webs/other/todos-oracle/.meteor/local/build/programs/server/profile.js:301:28)
W20170111-13:44:03.670(1)? (STDERR)     at /Users/martosj/Dev/Webs/other/todos-oracle/.meteor/local/build/programs/server/boot.js:304:13
W20170111-13:44:03.670(1)? (STDERR)     at /Users/martosj/Dev/Webs/other/todos-oracle/.meteor/local/build/programs/server/boot.js:345:5
W20170111-13:44:03.670(1)? (STDERR)     at Function.run (/Users/martosj/Dev/Webs/other/todos-oracle/.meteor/local/build/programs/server/profile.js:480:12)
W20170111-13:44:03.670(1)? (STDERR)     at /Users/martosj/Dev/Webs/other/todos-oracle/.meteor/local/build/programs/server/boot.js:343:11
=> Exited with code: 1

```

What am I missing?

**Comment by metstrike** [comment]
Hello, it looks like the library worked with meteor 1.3 and needs to be adjusted to work correctly with meteor 1.4. How how did you fix the "meteor update", I am getting the same error as you reported above.

**Comment by gazpachu** [comment]
TBH, I don't know how I did it. I think I typed everything it came to my mind until it let me update. Sorry, I know this is not very helpful.
